import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const accent = localFont({ 
  src: "./fonts/CSTM-Xprmntl-02-Italic-Web.woff2", 
  variable: "--font-accent",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/dfq8hts.css" />
      </head>
      <body className={`${accent.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
